AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - sit
      - prod
  NetworkStackName:
    Type: String
    Default: network-stack
  
Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Sub config-repository-${Environment}
      TaskDefinition:
        Fn::ImportValue:
          !Sub 'config-ecs-task-definition:TaskDefinitionConfig:${Environment}'
      LaunchType: FARGATE
      ServiceName: config-svc
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub '${NetworkStackName}:config:${Environment}'
          Subnets: !Split [',', Fn::ImportValue: !Sub '${NetworkStackName}:PublicSubnets:${Environment}' ]
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags: [ ]
      EnableECSManagedTags: true
Outputs:
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
